[ClassVersion("1.0.0"), FriendlyName("cPowerShellModuleManagement")] 
class TYConsulting_cPowerShellModuleManagement : OMI_BaseResource
{
  [Key, Description("The name of the PowerShell Repository")] string RepositoryName;
  [write, ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] string Ensure;
  [Key, Description("The name of the PowerShell module. Use value 'All' to specify all modules in the repository.")] string PSModuleName;
  [write, Description("The PowerShell module version.")] string PSModuleVersion;
};